### ISSUE TITLE
Resolutions

### ISSUE THREAD

**Issue by iSentrie** [boostless/Boost-DynamicHud#2]
Unsupported resolutions, ultrawide especially
![image](https://user-images.githubusercontent.com/29688478/189601620-ab8c8331-3df6-4e58-9245-5a858aa40cb4.png)
Maybe there is a way to adjust by radar position.

With help of this?:
https://cookbook.fivem.net/2019/08/12/useful-snippet-getting-the-top-left-of-the-minimap-in-screen-coordinates/

**Comment by boostless** [comment]
What is the resolution you are using ?

**Comment by iSentrie** [comment]
![image](https://user-images.githubusercontent.com/29688478/189602525-ce0e4b6a-8051-42d9-80d3-5816237f1551.png)

2560x1080

`/fixui` aligns it just by few pixels, still almost at the same place

Maybe this would help? https://github.com/Dalrae1/MinimapPositionFiveM

EDIT: tested with ^, looks like it works

**Comment by boostless** [comment]
I've added new minimap position finder you can test it out

**Comment by iSentrie** [comment]
> 

works just fine now, however u closed other issue about
![image](https://user-images.githubusercontent.com/29688478/189755354-95f64bcf-15fc-40a8-96fe-43dfd69e927f.png)

**Comment by boostless** [comment]
When it begins the spam ?

**Comment by iSentrie** [comment]
After spawning in.
After restarting resource.
Idk, just always.
